### ISSUE TITLE
[Enhancement] Neater Design!

### ISSUE THREAD

**Issue by karimawi** [Florry/spicetify-playlist-filter#8]
Hey, I was hoping if you could redesign the filter text input box to be more integrated into the app, I use Comfy as a theme, and it looks kinda off to me, I'd prefer if there was a magnifying glass icon next to the word "Playlists" that when clicked would first remove the word "Playlists" then expand a search bar for the user to type in with colors inherited from the installed theme

kinda like this:

![Spotify_UawhVke5Rh](https://user-images.githubusercontent.com/69881381/216799729-f03f6cf4-e3bc-4e9c-8d12-1a58e0400674.gif)

**Comment by Florry** [comment]
I'll see what I can do!

**Comment by karimawi** [comment]
I appreciate it!

**Comment by karimawi** [comment]
The new Xlibrary UI now has this built-in
